# Generated by Django 5.2.5 on 2025-08-09 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tggroup_alter_tginviteruser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_chat_id', models.BigIntegerField(verbose_name='Admin ChatID')),
                ('user_full_name', models.CharField(max_length=256, verbose_name='Admin F.I.Sh')),
                ('tg_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tggroup', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Guruh admini',
                'verbose_name_plural': 'Guruh adminlari',
            },
        ),
    ]
