# Generated by Django 5.2.5 on 2025-08-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_groupadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TgInviterUser',
        ),
        migrations.AlterField(
            model_name='tggroup',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Adminmi'),
        ),
    ]
