# Generated by Django 5.2.5 on 2025-08-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_delete_tginviteruser_alter_tggroup_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name="So'z")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "So'z",
                'verbose_name_plural': "So'zlar",
            },
        ),
    ]
