# Generated by Django 5.2.5 on 2025-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_blockedword'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('full_name', models.CharField(max_length=256, verbose_name="To'liq ism")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
        ),
    ]
