# Generated by Django 5.2.5 on 2025-08-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_tguser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.CreateModel(
            name='TgInviterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_chat_id', models.BigIntegerField(verbose_name='Qo‘shgan foydalanuvchi ChatID')),
                ('inviter_full_name', models.CharField(max_length=256, verbose_name='Qo‘shgan foydalanuvchi F.I.Sh')),
                ('invite_count', models.PositiveIntegerField(default=0, verbose_name='Qo‘shgan odamlar soni')),
                ('last_invite_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi qo‘shgan vaqti')),
                ('is_allow', models.BooleanField(default=False, verbose_name='Ruxsat berilganmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozuv yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yozuv yangilangan vaqti')),
                ('tg_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviters', to='bot.tggroup', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Odam qo‘shgan foydalanuvchi',
                'verbose_name_plural': 'Odam qo‘shgan foydalanuvchilar',
                'unique_together': {('tg_group', 'inviter_chat_id')},
            },
        ),
    ]
