# Generated by Django 5.2.5 on 2025-08-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_tguser_options_tginviteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tggroup',
            name='invite_count',
            field=models.IntegerField(default=0, verbose_name="Majburiy a'zo qo'shish"),
        ),
        migrations.AddField(
            model_name='tggroup',
            name='required_channel',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tggroup',
            name='required_channel_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tggroup',
            name='required_channel_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
