# Generated by Django 5.2.5 on 2025-08-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_tggroup_invite_count_tggroup_required_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(verbose_name='Kanal ID')),
                ('user_chat_id', models.BigIntegerField(verbose_name='Foydalanuvchi ChatID')),
                ('full_name', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Kanal a'zosi",
                'verbose_name_plural': "Kanal a'zolari",
                'unique_together': {('channel_id', 'user_chat_id')},
            },
        ),
    ]
