# Generated by Django 5.2.5 on 2025-08-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_channelmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_from_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Forward kelgan chat ID')),
                ('forward_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Forward kelgan xabar ID')),
                ('target_type', models.CharField(choices=[('groups', 'Guruhlar'), ('users', 'Foydalanuvchilar')], max_length=20)),
                ('created_by', models.BigIntegerField(verbose_name='Admin ChatID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
