# Generated by Django 5.2.5 on 2025-08-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Bot adminimi?'),
        ),
    ]
