# Generated by Django 5.2.5 on 2025-08-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_tguser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='error',
            field=models.IntegerField(default=0, verbose_name='Yuborilmadi'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='success',
            field=models.IntegerField(default=0, verbose_name='Muvaffaqqiyatli'),
        ),
        migrations.CreateModel(
            name='AdvertisementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.advertisement', verbose_name='Reklama')),
            ],
        ),
    ]
