# Generated by Django 5.2.5 on 2025-08-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_advertisement_error_advertisement_success_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementHistory',
        ),
    ]
