# Generated by Django 5.2.5 on 2025-08-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_delete_advertisementhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='ChatID')),
                ('title', models.CharField(max_length=256, verbose_name='Nomi')),
                ('is_success', models.BooleanField(default=False, verbose_name='Status')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.advertisement', verbose_name='Reklama')),
            ],
        ),
    ]
