# Generated by Django 5.2.5 on 2025-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_advertisementhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementhistory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh / Xato sababi'),
        ),
    ]
