# Generated by Django 5.2.5 on 2025-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_advertisementhistory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Bot adminimi?'),
        ),
    ]
